import { NextRequest, NextResponse } from "next/server";
import { Pinecone } from "@pinecone-database/pinecone";

/**
 * /api/clip-recommend
 *
 * Vector similarity search endpoint for Jewellos.
 * Receives a 512-dim visual embedding generated by Transformers.js
 * in the client browser, queries the Pinecone index, and returns
 * the closest matching earrings from the inventory.
 *
 * POST  application/json  { vector: number[], top_k?: number }
 */

const PINECONE_API_KEY = process.env.PINECONE_API_KEY;
const PINECONE_INDEX_NAME = process.env.PINECONE_INDEX_NAME || "jewellos";

let pineconeClient: Pinecone | null = null;

function getPineconeClient(): Pinecone {
  if (!PINECONE_API_KEY) {
    throw new Error(
      "PINECONE_API_KEY is not configured in environment variables."
    );
  }
  if (!pineconeClient) {
    pineconeClient = new Pinecone({ apiKey: PINECONE_API_KEY });
  }
  return pineconeClient;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => null);

    if (!body || !Array.isArray(body.vector) || body.vector.length === 0) {
      return NextResponse.json(
        { error: "Invalid request. Expected { vector: number[], top_k?: number }" },
        { status: 400 }
      );
    }

    const vector: number[] = body.vector;
    const topK: number = typeof body.top_k === "number" ? body.top_k : 3;

    const pc = getPineconeClient();
    const index = pc.index(PINECONE_INDEX_NAME);

    const queryResponse = await index.query({
      vector,
      topK,
      includeMetadata: true,
    });

    const matches = (queryResponse.matches || []).map((match) => {
      const meta = (match.metadata ?? {}) as Record<string, any>;
      // Convert cosine similarity score to a 0-100 scale
      const rawScore = match.score ?? 0;
      const scorePercent = Math.round(Math.max(0, Math.min(1, rawScore)) * 1000) / 10;

      return {
        id: match.id,
        score: scorePercent,
        name: (meta.name as string) || `Earring ${match.id}`,
        image: (meta.image as string) || `${match.id}.jpg`,
      };
    });

    return NextResponse.json({
      matches,
      model: "Xenova/clip-vit-base-patch32",
    });
  } catch (err: any) {
    console.error("Vector search error in /api/clip-recommend:", err);
    return NextResponse.json(
      {
        error:
          err?.message ||
          "Could not retrieve visual matches from vector database.",
      },
      { status: 500 }
    );
  }
}
